#!/bin/sh

# Hook the Cgminer Configuration + /etc/init.d/cgminer restart
echo '' >> /etc/config/ucitrack
echo 'config cgminer' >> /etc/config/ucitrack
echo -e '\toption init cgminer' >> /etc/config/ucitrack

# Enable the cgminer service
/etc/init.d/cgminer enable

# Disable ntp service (Run once when start cgminer)
/etc/init.d/sysntpd disable

# Setup the cron job
echo "*/3 *  *   *   *     /usr/bin/cgminer-monitor" | crontab -
if [ -f /usr/bin/cgminer-collect ]; then
    cron_job="*/5 *  *   *   *     /usr/bin/cgminer-collect"
    ( crontab -l | grep -v "$cron_job"; echo "$cron_job" ) | crontab -
fi

/etc/init.d/cron enable
/etc/init.d/cron stop
/etc/init.d/cron start
